title: lucasfacci.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Lucas Facci
url: "https://lucasfacci.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title:output_ext
